# ----------------
#language: python #works on Linux, but not osx, win
#language: ruby
#python:
#  - 3.6
os: osx
#matrix:
#  include:
#    - name: "Python 3.8 dev"
#      python: 3.8-dev
#      xenial: trusty
#      env: PYTHON=python3 PIP=pip3  # Unnecessary on Lunixinstall:
#  - pip install -r requirements.txt
install:
  - pip3 install -r requirements.txt
  #- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  #- export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  #- brew install python
script:
  # system info
  - uname -a
  # Qt
  - brew tap cartr/qt4
  - brew tap-pin cartr/qt4
  - brew install cartr/qt4/qt
  - brew install cartr/qt4/pyqt  
  - sudo find /usr /opt -type f -name qmake -ls
  - qmake --version # Qt version
  # python
  - python --version
  - python3 --version
  - pip3 list --format=columns # List installed packages
  - cat test01.py
  - python3 test01.py
  # ccache
  - ls -l /usr
  - sudo find /usr /opt -type f -name ccache -ls
  - brew install ccache
  - sudo find /usr /opt -type f -name ccache -ls # /usr/local/Cellar/ccache/3.7.6/bin/ccache
  - export PATH=/usr/local/Cellar/ccache/3.7.6/bin/ccache:$PATH
  - ccache --version


# osx python
#https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
