# ----------------
language: python #works on Linux, but not osx, win
#language: ruby
#python:
#  - 3.6
os: osx
#matrix:
#  include:
#    - name: "Python 3.8 dev"
#      python: 3.8-dev
#      xenial: trusty
#      env: PYTHON=python3 PIP=pip3  # Unnecessary on Lunixinstall:
#  - pip install -r requirements.txt
install:
  - pip3 install -r requirements.txt
  #- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  #- export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  #- brew install python
script:
  - python --version
  - python3 --version
  - ls -l /usr
  - sudo find /usr -type f -name ccache -ls
  - uname -a
  - cat test01.py
  - python3 test01.py


# osx python
#https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
