# ----------------
os: linux
language: c++
  - fortran
  
before_install: 
  - echo "------------------------before_install"

install:
  - echo "------------------------install"
  
script:
  # script
  - echo "------------------------script"
  - if [[ $TRAVIS_OS_NAME == linux ]]; then 
      source travis_check_gnucap.sh $TRAVIS_OS_NAME ;
    fi 
