# ----------------
os: linux
language: c++

before_install: 
  - echo "------------------------before_install"

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then 
      echo "---------------------------install";
      source ./travis_check_gnucap.sh $TRAVIS_OS_NAME;
    fi 

script:
  # system info
  - echo "--------------------------------------------------------Sys----------------------------------------------------"
  - uname -a
  # Qt
  - echo "--------------------------------------------------------Qt----------------------------------------------------"
  - sudo find /usr /opt -type f -name qmake -ls
        # /usr/local/Cellar/qt/5.13.2/bin/qmake
        # /usr/local/Cellar/qt@4/4.8.7_6/bin/qmake
  - qmake --version # Qt version #Using Qt version 4.8.7 in /usr/local/lib
  # clang
  - echo "--------------------------------------------------------clang----------------------------------------------------"
  - clang --version
  # ccache
  - echo "--------------------------------------------------------ccache----------------------------------------------------"
  - ls -l /usr
  - sudo find /usr /opt -type f -name ccache -ls # /usr/local/Cellar/ccache/3.7.6/bin/ccache
  - ccache --version

