# ----------------
os: linux
language: c++

before_install: 
  - echo "------------------------before_install"

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then 
      echo "---------------------------install";
      ls -la;
      source travis_check_gnucap.sh $TRAVIS_OS_NAME ;
    fi 

script:
  # script
  - echo "------------------------script"
