# ----------------
os: osx
osx_image: xcode11.3
#matrix:
#  include:
#    - name: "Python 3.8 dev"
#      python: 3.8-dev
#      xenial: trusty
#      env: PYTHON=python3 PIP=pip3  # Unnecessary on Lunixinstall:
#  - pip install -r requirements.txt
before_install:
  - source travis_check_qt.sh $TRAVIS_OS_NAME
  #- source travis_check_py.sh $TRAVIS_OS_NAME
  #- source travis_check_cpp.sh $TRAVIS_OS_NAME
install:
  - pip3 install -r py/requirements.txt
  #- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  #- export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  #- brew install python
script:
  # system info
  - echo "--------------------------------------------------------Sys----------------------------------------------------"
  - uname -a
  # Qt
  - echo "--------------------------------------------------------Qt----------------------------------------------------"
  - brew tap cartr/qt4
  #- brew tap-pin cartr/qt4 # Error: Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead.
  - brew install cartr/qt4/qt
  - brew install cartr/qt4/pyqt  
  - sudo find /usr /opt -type f -name qmake -ls
        # /usr/local/Cellar/qt/5.13.2/bin/qmake
        # /usr/local/Cellar/qt@4/4.8.7_6/bin/qmake
  - qmake --version # Qt version #Using Qt version 4.8.7 in /usr/local/lib
  - sudo find /usr /opt -iname "*Qt3Support*" -ls
  # python
  - echo "--------------------------------------------------------python----------------------------------------------------"
        # https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - python --version     # Python 2.7.17
  - python3 --version    # Python 3.7.5
  - pip3 list --format=columns # List installed packages
  - cat test01.py
  - python3 test01.py
  # clang
  - echo "--------------------------------------------------------clang----------------------------------------------------"
  - clang --version
  # ccache
  - echo "--------------------------------------------------------ccache----------------------------------------------------"
  - ls -l /usr
  - sudo find /usr /opt -type f -name ccache -ls
  - brew install ccache
  - sudo find /usr /opt -type f -name ccache -ls # /usr/local/Cellar/ccache/3.7.6/bin/ccache
  - export PATH=/usr/local/Cellar/ccache/3.7.6/bin/ccache:$PATH
  - ccache --version
  # flex
  - echo "--------------------------------------------------------flex----------------------------------------------------"
  - flex --version
  # bison
  - echo "--------------------------------------------------------bison----------------------------------------------------"
  - bison --version

