# ----------------
os: linux
language: python #works on Linux, but not osx, win
#sudo: false

before_install: 
  - export PYTHON_VERS="3.7.5"

python: 3.7.5 # in case there are many 3.7 versions travis aborts
    
install:
  - pip3 install -r requirements.txt
  - if [[ $TRAVIS_OS_NAME == linux ]]; then 
      pip3 install --upgrade setuptools ; 
      pip3 install numpy matplotlib ; 
    fi   

script:
  # system info
  - echo "--------------------------------------------------------Sys----------------------------------------------------"
  - uname -a
  # Qt
  - echo "--------------------------------------------------------Qt----------------------------------------------------"
  - sudo find /usr /opt -type f -name qmake -ls
        # /usr/local/Cellar/qt/5.13.2/bin/qmake
        # /usr/local/Cellar/qt@4/4.8.7_6/bin/qmake
  - qmake --version # Qt version #Using Qt version 4.8.7 in /usr/local/lib
  # python
  - echo "--------------------------------------------------------python----------------------------------------------------"
        # https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - python --version     # Python 2.7.17
  - python3 --version    # Python 3.7.5
  -     
  - cat test01.py
  - python3 test01.py
  # clang
  - echo "--------------------------------------------------------clang----------------------------------------------------"
  - clang --version
  # ccache
  - echo "--------------------------------------------------------ccache----------------------------------------------------"
  - ls -l /usr
  - sudo find /usr /opt -type f -name ccache -ls # /usr/local/Cellar/ccache/3.7.6/bin/ccache
  - ccache --version
  # flex
  - echo "--------------------------------------------------------flex----------------------------------------------------"
  - flex --version
  # bison
  - echo "--------------------------------------------------------bison----------------------------------------------------"
  - bison --version

