# ----------------
os: linux
language: c++

before_install: 
  - echo "------------------------before_install"

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then 
      echo "---------------------------install";
      ls -la;
      source travis_check_gnucap.sh $TRAVIS_OS_NAME ;
    fi 

script:
  # clang
  - echo "--------------------------------------------------------clang----------------------------------------------------"
  - clang --version # 20200417: clang version 7.0.0 (tags/RELEASE_700/final)
  # ccache
  - echo "--------------------------------------------------------ccache----------------------------------------------------"
  #- ls -l /usr
  #- sudo find /usr /opt -type f -name ccache -ls # /usr/local/Cellar/ccache/3.7.6/bin/ccache
  - ccache --version

