######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 23 14:21:29 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
